DATALOADER:
  TRAIN_X:
    BATCH_SIZE: 8
  TEST:
    BATCH_SIZE: 100
  NUM_WORKERS: 8
  RETURN_IMG0: True
  K_TRANSFORMS: 4

INPUT:
  SIZE: (224, 224)
  INTERPOLATION: "bicubic"
  PIXEL_MEAN: [0.48145466, 0.4578275, 0.40821073]
  PIXEL_STD: [0.26862954, 0.26130258, 0.27577711]
  TRANSFORMS: ["random_resized_crop", "random_flip", "normalize"]
  RRCROP_SCALE: (0.4, 1.0)

OPTIM:
  NAME: "sgd"
  LR: 0.0025
  MAX_EPOCH: 20
  LR_SCHEDULER: "cosine"
  WARMUP_EPOCH: 1
  WARMUP_TYPE: "constant"
  WARMUP_CONS_LR: 1e-5

TRAIN:
  PRINT_FREQ: 20

MODEL:
  BACKBONE:
    NAME: "ViT-B/16"

TRAINER:
  TAC:
    N_CTX_VISION: 5
    N_CTX_TEXT: 5
    CTX_INIT: "a photo of a"
    PREC: "fp16"
    PROMPT_DEPTH_VISION: 12
    PROMPT_DEPTH_TEXT: 12
    TEXT_LOSS_WEIGHT: 20
    IMAGE_LOSS_WEIGHT: 25